### ISSUE TITLE
gmapQ id<#MyInterface>

### ISSUE THREAD

**Issue by o1lo01ol1o** [eiriktsarpalis/TypeShape#12]
Hi,
  First, thanks so much for this library, having robust generic programming in F# really smooths some tasks over for me.  

Second, I'm trying to implement a version of gmapQ that will apply its function to any type  that implements a given interface but I can't seem to figure out how to specify this, could you advise?

Thanks

**Comment by eiriktsarpalis** [comment]
Hi! You could try using [this function](https://github.com/eiriktsarpalis/TypeShape/blob/33be43d8c9ae76e6e5d9c8df7748a3fc2156c12f/src/TypeShape/SubtypeExtensions.fs#L11). NB this introduces a dependency on additional [C# code](https://github.com/eiriktsarpalis/TypeShape/blob/33be43d8c9ae76e6e5d9c8df7748a3fc2156c12f/src/TypeShape.CSharp/ShapeSubtype.cs) due to restrictions in subtyping contraints in F#.

**Comment by o1lo01ol1o** [comment]
Thanks, that gets me one step closer: I can match on the case when a shape has a base interface, however, the wrap function throws an invalid cast error.  

The following amedment to the `gmapQ` code:

[. . .]
```fsharp
match shapeof<'U> with
        | :? TypeShape<'T> -> wrap(fun (t:'T) -> [f t])
        | m when (Shape.tryCreateSubtypeShape<'T> (m)).IsSome -> 
            m.Accept { new ITypeShapeVisitor<'U -> 'S list> with 
                member __.Visit () = wrap (List.singleton) } 

```
[. . . ]

 when called with `gmapIQ id<IMyInterface> s` throws:

```
System.InvalidCastException: 'Unable to cast object of type 'gmapIQ@236-2[IMyInterface]' to type 'Microsoft.FSharp.Core.FSharpFunc`2[ImplementsIMyInterface,Microsoft.FSharp.Collections.FSharpList`1[IMyInterface]]'.'
```

I'm not exactly where the issue is, my thought is that I need to explicitly cast `'U :> 'S` in the above case but I can't seem to prove to the compiler that this is a valid coercion.  Any thoughts?

**Comment by eiriktsarpalis** [comment]
Here's how it could be written:
```fsharp
    let (|Subtype|_|) = Shape.tryCreateSubtypeShape<'T> 

    match shapeof<'U> with
    | Subtype s ->
        s.Accept { new ISubtypeVisitor<'T, 'U -> 'S list> with
            member this.Visit<'U0 when 'U0 :> 'T>() =
                wrap(fun (u:'U0) -> [f u])
        }
```
*However*, due to restrictions in how F# deals with subtype constraints, the code above fails to compile. This is because the `'T` type cannot be generic. I don't think there's a way to overcome this. /cc @dsyme

**Comment by eiriktsarpalis** [comment]
Turns out you can trick the compiler to make this work. Here's the PR that fixes it and updates gmapQ to support it: https://github.com/eiriktsarpalis/TypeShape/commit/0e129f706df30655ae7ec9cb52e04934d886755a

**Comment by o1lo01ol1o** [comment]
Sweet, working.

But it's not really "tricking" if you provide a `witness`, is it?
