### ISSUE TITLE
Matching of union property names with their backing fields broken for F# 4.1

### ISSUE THREAD

**Issue by deneuxj** [eiriktsarpalis/TypeShape#14]
### Description

Attempting to serialize a union with named fields with FsPickler sometimes fails. The cause appears to be in TypeShape.fs

### Repro steps

The following program throws an exception, using head of FsPickler and Visual Studio 15.5.2

```
open System.IO
open MBrace.FsPickler

type ExecutionState =
    | Failed of AC:string option

[<EntryPoint>]
let main2 argv =
    let v = Failed None

    let serializer = FsPickler.CreateXmlSerializer(indent = true)
    use mem = new System.IO.MemoryStream()
    use s = new StreamWriter(mem)
    serializer.Serialize(s, v) // Throws an exception

    0
```

### Expected behavior

The program should run without exceptions

### Actual behavior

The program throws an exception

### Known workarounds

Remove the name of the field `AC`, or change the name to lower case. I'm not sure exactly what names work and which ones don't. It seems it has to do with upper-case letters.

Editing TypeShape.fs around line 1501 to get the following fixed my problem, not sure if it's a general fix.
```
    let caseFields =
        match properties with
        | [||] -> [||]
        | _ ->
            let underlyingType = properties.[0].DeclaringType
            let allFields = underlyingType.GetFields(allInstanceMembers)
            let mkUnionField (p : PropertyInfo) =
                let fieldInfo = allFields |> Array.find (fun f -> f.Name = "_" + p.Name || f.Name = p.Name.ToLower() || f.Name = p.Name.[0..0].ToLower() + p.Name.Substring(1)) // < this line changed
                mkWriteMemberUntyped<'Union> p.Name p [|fieldInfo|]

```
### Related information 

* Operating system: Win10 Home
* Branch: master
* .NET Runtime, CoreCLR or Mono Version: .net 4.6
* Performance information, links to performance testing scripts: Not relevant

**Comment by deneuxj** [comment]
Another way to reproduce the problem, using a test in FsPickler: https://github.com/mbraceproject/FsPickler/pull/99

**Comment by eiriktsarpalis** [comment]
The error is not reproducible here, it seems to be happening in FsPickler because it's referencing an older version of TS
