### ISSUE TITLE
Two errors in the first example.

### ISSUE THREAD

**Issue by mrakgr** [eiriktsarpalis/TypeShape#2]
```
    | Shape.Array s ->
        s.Accept {
            new IArrayVisitor<'T -> string> with
                member __.Visit<'a> () =
                    let tp = mkPrinter<'a> ()
                    wrap(fun ts -> ts |> Array.map tp |> String.concat "; " |> sprintf "[|%s|]")
        }
```
Here it gives me an error that this interface expects one argument.

The other error is that when I try to run the first parser example it throws an exception because Tuple3 is not implemented.

Apart from the above, I am wondering why are those interface objects necessary? Wouldn't standard functions suffice?

This is quite an interesting technique and I am considering using it to implement the API for the Cuda modules in my ML library. I was really quite struggling on how to implement it until somebody posted the parser example to the F# subreddit. The problem is that I can just write a `Array.map (fun x -> x*x)` like in standard F# code, but have to specify a host of other parameters as lambdas instead. I did not know how to generate them automatically from the lambda's type. 

I am hoping it might be possible using TypeShape.

**Comment by eiriktsarpalis** [comment]
The example in the readme contains older versions of the api and hasn't been updated. I fixed the error that you mentioned. Please refer to the samples folder for more up-to-date implementations.

Standard F# functions are not sufficient for encoding this pattern since they do not allow higher-rank types. See [this post](http://stackoverflow.com/a/7221589) for a more detailed explanation.

**Comment by mrakgr** [comment]
Ok, thanks. Maybe it would be good to fix the tuple error on the main page as well? I see that the printer example in the `.fsx` file works just fine.

**Comment by eiriktsarpalis** [comment]
What is the error? Do you mean to say 3-tuples are not implemented? This is intentionally omitted for brevity reasons.

**Comment by mrakgr** [comment]
Yeah, I meant that. If the code on the main page is not supposed to be run, then I guess it is fine.

**Comment by eiriktsarpalis** [comment]
Thank you for your feedback. Let me know if you have any other questions
