### ISSUE TITLE
Nuget package 6.1.0 has dependency on Microsoft.SourceLink.GitHub

### ISSUE THREAD

**Issue by marklam** [eiriktsarpalis/TypeShape#22]
### Description

Installing version 6.1.0 creates a dependency on Microsoft.SourceLink.GitHub, and causes build warnings if your project is not under git source control

Presumably the  Microsoft.SourceLink.GitHub package should be excluded from TypeShape's nuget dependencies

### Repro steps

1. paket update

### Known workarounds

Stay at version 6.0.1

### Related information 

* Windows 10
* Paket
* Visual Studio 2017

**Comment by eiriktsarpalis** [comment]
Fixed, will be released as 6.1.1
