### ISSUE TITLE
Add link to schemaless data contracts article from IUnionContract?

### ISSUE THREAD

**Issue by bartelink** [eiriktsarpalis/TypeShape#27]
I'd like to slip a 
`/// see https://eiriktsarpalis.wordpress.com/2018/10/30/a-contract-pattern-for-schemaless-datastores/ for an overview`

into the middle of:

```
/// Marker interface for tagging union contract types
type IUnionContract = interface end
```

on the basis that we make use of this in lots of places where the reader will have no idea what a "union contract type" might be; being able to provide such a well written overview at such a teachable moment would make my personal life better. Happy to do a PR (and equally happy for you to lolnope it)

**Comment by eiriktsarpalis** [comment]
Sure, sounds good!
