### ISSUE TITLE
Github Releases not containing release notes

### ISSUE THREAD

**Issue by haf** [eiriktsarpalis/TypeShape#29]
### Description

Neither [releases](https://github.com/eiriktsarpalis/TypeShape/releases) nor the README contains any help on what changes between versions. I could read the code and try to deconstruct it, but it would be more helpful to have release notes on what changed and how to upgrade. I see e.g. that `shapeof` is changed to return with a generic parameter, there's a new HKT ns and some things have plainly gone missing.

**Comment by eiriktsarpalis** [comment]
I believe the changes you're referring to haven't been released in a nuget though.

**Comment by haf** [comment]
Right, I'm using source code references for Logary to avoid the dependency. But it's been released as v7.1.

**Comment by eiriktsarpalis** [comment]
Looks like the 7.1 tag is off. But this is what I see in the [nuget package](https://www.nuget.org/packages/TypeShape/7.1.0):
> Expose IsAnonymousRecord property for F# record shapes.

What else has been changed?

**Comment by haf** [comment]
`shapeof` now returns `TypeShape<'t>` and I think a few `Visit` members disappeared — try upgrading Logary's TypeShape to have a look yourself; I may be missing details since I reverted as soon as I could.

**Comment by eiriktsarpalis** [comment]
Basically [this change](https://github.com/eiriktsarpalis/TypeShape/commit/9589d5c539dc133de7df4de2add5ff2ed838c2e1) which is dated July 20. The [7.1 tag](https://github.com/eiriktsarpalis/TypeShape/commit/9f34947be23e3383a73539bc8a4033e49bc6ead2) is dated June 30. I think you probably just fetched the head of master?

**Comment by haf** [comment]
Yes, Paket has a bug that fetches the head of master, so I did that and got a lot of breakage. Then I tried to downgrade to 7.1 which was the latest release and didn't seem to have that change in it, but then there was a whole bunch of other commits and no release notes for 7.1, so filed this issue.

**Comment by eiriktsarpalis** [comment]
Yes the 7.1 release seems off. Not sure why, probably rusty build infrastructure.
