### ISSUE TITLE
"Unsupported type" exception with TypeSafe sample type

### ISSUE THREAD

**Issue by object** [eiriktsarpalis/TypeShape#3]
### Description

"Unsupported type" exception when using TypeSafe.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a console app or an FSX script.

2. Use sample class for value printer (as published on the front page of this repo)

3. Place a statement
let p = mkPrinter&lt;TestType&gt;()

### Expected behavior

Should create a value printer for the type TestType.

### Actual behavior

The statement above causes exception: 
Unhandled Exception: System.Exception: unsupported type 'System.Tuple`3[Microsoft.FSharp.Collections.FSharpList`1[System.Int32],Microsoft.FSharp.Core.FSharpOption`1[System.String],System.String]'
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1360.Invoke(String message)
   at Program.mkPrinter[T]() in C:\Projects\Temp\TypeShapeTest\TypeShapeTest\Program.fs:line 54
   at Program.mkPrinter@22-8.TypeShape-ITuple2Visitor`1-Visit[t1,t2]() in C:\Project\Temp\TypeShapeTest\TypeShapeTest\Program.fs:line 25
   at TypeShape.ShapeTuple2`2.TypeShape-IShapeTuple2-Accept[a](ITuple2Visitor`1v) in C:\Projects\Temp\TypeShapeTest\TypeShapeTest\TypeShape.fs:line 288
   at Program.mkPrinter[T]() in C:\Projects\Temp\TypeShapeTest\TypeShapeTest\Program.fs:line 22
   at Program.main(String[] argv) in C:\Projects\Temp\TypeShapeTest\TypeShapeTest\Program.fs:line 68

### Known workarounds

No workaround.

### Related information 

* Windows 8.1
* Visual Studio 2015
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by eiriktsarpalis** [comment]
This will generate a printer for `obj`, which has not been implemented in that particular sample. Try adding an angle bracket which specifies the type you need to generate a printer for.

**Comment by object** [comment]
I actually used angle brackets, but they disappeared here due to the formatting. I've restored them now.
So basically I am doing just as described on the front page, with angle brackets. Still get this exception.

**Comment by object** [comment]
![bilde](https://cloud.githubusercontent.com/assets/252126/23553135/bc42f1ca-001f-11e7-9d6b-7b0e65730534.png)

**Comment by eiriktsarpalis** [comment]
Right, the sample in `README.md` is intentionally incomplete for brevity reasons. Try using printer.fsx in the `samples` folder for a more extensive implementation.

**Comment by object** [comment]
Yes, this worked fine. Thank you for a quick response. I suggest to update the README.md with the working sample or making a note there so people know what to use.

**Comment by cotyar** [comment]
Hi Eirik, thank you for the awesome library!

Some of the examples (like printer) don't like byte[]'s in unions and records at least on Mono.
Int arrays work fine the same time.

**Comment by eiriktsarpalis** [comment]
@cotyar I imagine you mean the example in README.md? it seems to be working for the fsx sample.

**Comment by cotyar** [comment]
@eiriktsarpalis no, had problems with the fsx-s failing with method not supported or similar exception.
Yesterday found the same issue with record and DU arrays/lists. 
On Monday will be able to test it again on Mono/CoreCLR and will update here with the results.

**Comment by cotyar** [comment]
Sorry, my bad. All works.

**Comment by bartelink** [comment]
This issue seems to be closable ?
