### ISSUE TITLE
ios version?

### ISSUE THREAD

**Issue by vshapenko** [eiriktsarpalis/TypeShape#30]
Hello! Recently i've written an bson mapper for DbLite based on TypeShape:
https://github.com/Zaid-Ajaj/LiteDB.FSharp/blob/master/LiteDB.FSharp/TypeShapeMapper.fs

The problem is it does not work on ios(IPhone) in case of TYPESHAPE_EMIT related code (mostly Shape.createUninitialized)

Is where a way to somehow make this work? (using another method to create uninitialized value etc)

**Comment by eiriktsarpalis** [comment]
I haven't used Xamarin but I'm pretty certain that dynamic IL generation is not supported in those runtimes. You'd probably have to disable that flag.

**Comment by Liminiens** [comment]
Maybe there is a way to add such global static flag or api to avoid the need of downloading a project and setting compilation flag directly?

**Comment by eiriktsarpalis** [comment]
The recommended approach for consuming in libraries is to [reference the source files directly](https://github.com/eiriktsarpalis/TypeShape#installing). Then you can set compile conditionals as desired and remove TypeShape as a package dependency.

Also, feel free to add your project in [this list](https://github.com/eiriktsarpalis/TypeShape#projects-using-typeshape).

**Comment by eiriktsarpalis** [comment]
> Maybe there is a way to add such global static flag or api to avoid the need of downloading a project and setting compilation flag directly?

Main concern with that is that it can interfere with multiple projects having the same reference.

**Comment by Liminiens** [comment]
Valid point. We are referencing the source directly now and have no problems with it (thanks to paket). It was just a thought that is there any way to make it work on library level via some public api.

**Comment by dzmitry-lahoda** [comment]
- As I know iOS is AOT. AOT usually drops some code accessed via reflection and must be specifically stated not to do so (like dummy usage of type or its members). 
- `TYPESHAPE_EMIT`, if it is `IL` emit or any kind of runtime compilation, does not work or buggy-slow(interpreter) in AOT. 
- I see the raise of AOT (Unity, WASM, IoT, ZeroSharp). 

Is it possible to split out compile time of `TypeShape` core with no runtime reflection or emit? It would be fine to retain runtime reflection, but only if it is done only once on start up (performance reasons).  May be provide some forms (helpers or providers) to reduce typing needed to manually fill reflection parts of code. Of course, if something like `TypeShape.Core` what ever possible without emit or reflection. 

Please do not consider my comment to seriously, thanks.

**Comment by eiriktsarpalis** [comment]
I might consider removing dynamic method generation in future releases. The reason is that in my benchmarks performance benefits are insignificant in .NET Core (unlike full framework).
