### ISSUE TITLE
Remove dynamic methods from core library

### ISSUE THREAD

**Issue by eiriktsarpalis** [eiriktsarpalis/TypeShape#32]
TypeShape uses dynamic methods to improve performance for generated lenses, generally following the [technique originally described here](https://codeblog.jonskeet.uk/2008/08/09/making-reflection-fly-and-exploring-delegates/). It helps provide up to 5x performance speedups when doing generic programming in full framework. However in .NET Core the performance benefits are marginal and in some cases using plain old reflection actually provides a modest speedup. 

While dynamic methods can be toggled using the `TYPESHAPE_EMIT` build conditional, the nuget package gets built with that flag enabled. Given the increasing adoption of .NET Core, I think it might make sense to completely remove dynamic methods in future releases. This comes with the added benefit of unblocking users who rely on AOT (c.f. #30). While this may result in performance degradation for full framework consumers, I feel it might be the right time to move on.

**Comment by DalekBaldwin** [comment]
I maintain some DSLs that use similar techniques; do you have any links with info on the relative performance in Framework vs. Core?

**Comment by eiriktsarpalis** [comment]
@DalekBaldwin  I haven't published any. Generally though I used the `TypeShape.Benchmarks` projects to extract the results.
