### ISSUE TITLE
Allow TypeGenerationContext to use additional key components beyond types of returned values

### ISSUE THREAD

**Issue by DalekBaldwin** [eiriktsarpalis/TypeShape#33]
TypeGenerationContext often imposes additional runtime and/or code complexity costs when creating multiple distinct functions of the same type is desirable, or when not all cached results' types are instantiations of a common generic type. I'll focus on the first case.

Consider a parser generator for:

``` fsharp
type Record1 =
    { SubRecordA : Record2
      SubRecordB : Record2 }

and Record2 =
    { ElementA : int
      ElementB : string }
```

Where the root element's name is assumed to be the same as the root type's name, but nested records are parsed using the field names, not type names:

``` xml
<Record1>
  <SubRecordA>
    <ElementB>"foo"</ElementB>
  </SubRecordA>
  <SubRecordB>
    <ElementB>"bar"</ElementB>
  </SubRecordB>
</Record1>
```

And we want to be able to create distinct error messages along the lines of: "Missing expected sub-element ElementA of element SubRecordA" or "Missing expected sub-element ElementA of element SubRecordB". To fully pre-generate parsers based on known information about the types, we really want keys that are a combination of types and ordinary values, like `("SubRecordA","ElementA",typeof<ActualXmlParserFunctionType<string>>)`.

In a straightforward implementation using the existing TypeGenerationContext, the parsers for distinct fields of the same type would have to be of the same type, and could have only one entry in the cache. This strongly influences the client code to use more complicated types and do more work at runtime (passing the name of the parent field to functions that produce the ultimate subparsers and appropriate exception messages for subfields, performing extra work and allocations, or carrying a "runtime stack" of field names) that could have been performed at an earlier stage, and/or to use a secondary external recursive caching mechanism that is difficult to correctly reason about in concert with TypeGenerationContext's own commit protocol. (My current workaround is to map the additional key components to distinctly-typed dummy arguments e.g. by a Peano-number type encoding so they receive distinct cache entries and keep TypeShape solely responsible for handling all the recursive knot-tying.)

I believe a nice interface could provided in a backward-compatible way with an additional overload for InitOrGetCachedValue like: `member __.InitOrGetCachedValue<'Key,'T> (key:'Key) (delay:Cell<'T> -> 'T) : CachedResult<'T>` (and likewise `Commit<'Key,'T>`), with minor modifications to the internal code, at no runtime cost for client code that follows existing conventions. Thoughts?

**Comment by DalekBaldwin** [comment]
I tried to make the most straightforward changes to test it out; the tests all pass on .Net Core, but on Framework it seems that FsCheck doesn't like it: https://github.com/DalekBaldwin/TypeShape/commit/6714adf3fbc23ed1f8a08c97552265cef01387b0

**Comment by eiriktsarpalis** [comment]
I see what you mean, my general approach to this problem has to modify the parser to accept the field name as an additional parameter.

To be very honest, the types in `Utils.fs` are meant to be simple helpers that power the basic samples included in the repo, as well as demonstrating in relatively simple terms how caching and recursive type support can be implemented. I would generally recommend implementing a bespoke caching solution in more involved scenaria (as I've done in FsPickler which uses TypeShape).
