### ISSUE TITLE
Is not compatible with .NET Core

### ISSUE THREAD

**Issue by cotyar** [eiriktsarpalis/TypeShape#5]
Great thanks for the awesome lib!

Unfortunately it yet doesn't work with .NET Core because of change in System.Reflection.
I tried to fix it and at least Mock and (slightly modified local) Printer example works with it.
Please the modified version attached.

Many thanks again,
Yuriy

[TypeShape.fs.zip](https://github.com/eiriktsarpalis/TypeShape/files/945784/TypeShape.fs.zip)

**Comment by eiriktsarpalis** [comment]
Thanks, I think we should wait until the release of netstandard2, which will bring back some of the deprecated APIs.

**Comment by cotyar** [comment]
Thanks Eirik,
Maybe put the version in the zip attached in "experimental" folder or something for now?
It so far does the job (at least for my cases) and has no changed in API compared to the original. 
So people who already migrated to the .NET Core could benefit from it.

PS. Your idea and implementation with this lib is just awesome! It still blows up my brain when I'm trying to use it but it properly cool ;-)

Fable supports a lot from the reflection. Would be interesting to migrate at least some of the stuff to it ... I wish I had more time 8-(

**Comment by bartelink** [comment]
It seems this should be closed ?
