### ISSUE TITLE
Add .net6 DateOnly

### ISSUE THREAD

**Issue by pkese** [eiriktsarpalis/TypeShape#50]
Dotnet 6 has added [DateOnly](https://docs.microsoft.com/en-us/dotnet/api/system.dateonly?view=net-6.0) type (besides DateTime), which is not supported.

**Comment by eiriktsarpalis** [comment]
`DateOnly` and `TimeOnly` are only available in the `net6.0` TFM, however the TypeShape library only targets `netstandard2.0` and `netcoreapp3.1` so it's currently not possible to offer OOTB support. The library is designed for extensibility, I would recommend writing your own active patterns for the desired types.

**Comment by eiriktsarpalis** [comment]
I pushed 736c4b56ebd949e2d27f04447200dd45d139e5f1 which extends the samples with net6.0 types.
