### ISSUE TITLE
Library form of the JSON serializer example?

### ISSUE THREAD

**Issue by justinwoo** [eiriktsarpalis/TypeShape#8]
### Description

Are there any plans to bring the [JSON serializer example](https://github.com/eiriktsarpalis/TypeShape/blob/master/samples/json-serializer.fsx) out into a full library? I would really like to use this or any other similar datatype generic approach to derive JSON serializers, and I haven't been able to find any yet

### Repro steps

* google "datatype generic json serialization in fsharp"

* only find an example by Vesa Karvonen and by Eirik Tsarpalis with Typeshape

### Expected behavior

* There should be a nice datatype generic JSON library

### Actual behavior

* There doesn't seem to be any actually used by many people

### Known workarounds

* Copy-pasting the example code and trying to do it manually

### Related information 

I would like to do something easily as I do in Purescript: https://github.com/justinwoo/purescript-howto-foreign-generic without manually defining the serialization manually (e.g. Chiron seems fine except for this crucial detail)

**Comment by eiriktsarpalis** [comment]
FsPickler.Json is an example of such a serializer. It uses Newtonsoft for basic tokenization/formatting but otherwise it is completely driven by TypeShape.
