### ISSUE TITLE
Include class methods in shapes

### ISSUE THREAD

**Issue by Horusiath** [eiriktsarpalis/TypeShape#9]
The current design is great when it comes to generic programming based on data-oriented schemas. Adding a support for methods recognition in shapes such as `IShapePoco`, `IShapeFSharpRecord` and `IShapeFSharpUnion` would be a great addition for systems, which would like to make use of generic programming spanned over callable members as well.

**Comment by eiriktsarpalis** [comment]
This has in part been realized with [constructor shapes](https://github.com/eiriktsarpalis/TypeShape/blob/master/src/TypeShape/TypeShape.fs#L1215). Extending this to arbitrary methods is a natural extension of this idea. The main drawback is that arguments need to be expressed in tupled form, which can incur performance penalties when invoking at runtime.
